window.SIMPLE_DATA = {
  "as_of": "2026-06-05",
  "generated": "2026-06-06 23:58Z",
  "benchmark": "SPY",
  "themes": [
    {
      "label": "Chips / Semiconductors",
      "etf": "SMH",
      "trend": "up",
      "ret3mo": 0.497,
      "vs_spy": 0.3971,
      "buzz": 91,
      "crowd": "loud",
      "state": "confirmed",
      "light": "green",
      "emoji": "\ud83d\udfe2",
      "verdict": "Uptrend and the crowd is piling in \u2014 the trend everyone agrees on."
    },
    {
      "label": "Cybersecurity",
      "etf": "CIBR",
      "trend": "up",
      "ret3mo": 0.3159,
      "vs_spy": 0.216,
      "buzz": 36,
      "crowd": "quiet",
      "state": "early",
      "light": "blue",
      "emoji": "\ud83d\udd35",
      "verdict": "Quietly trending up before the crowd noticed \u2014 the early ones."
    },
    {
      "label": "Space",
      "etf": "UFO",
      "trend": "up",
      "ret3mo": 0.2292,
      "vs_spy": 0.1292,
      "buzz": 77,
      "crowd": "loud",
      "state": "confirmed",
      "light": "green",
      "emoji": "\ud83d\udfe2",
      "verdict": "Uptrend and the crowd is piling in \u2014 the trend everyone agrees on."
    },
    {
      "label": "Solar",
      "etf": "TAN",
      "trend": "up",
      "ret3mo": 0.2021,
      "vs_spy": 0.1022,
      "buzz": 23,
      "crowd": "quiet",
      "state": "early",
      "light": "blue",
      "emoji": "\ud83d\udd35",
      "verdict": "Quietly trending up before the crowd noticed \u2014 the early ones."
    },
    {
      "label": "Big Tech",
      "etf": "QQQ",
      "trend": "up",
      "ret3mo": 0.1771,
      "vs_spy": 0.0772,
      "buzz": 55,
      "crowd": "loud",
      "state": "confirmed",
      "light": "green",
      "emoji": "\ud83d\udfe2",
      "verdict": "Uptrend and the crowd is piling in \u2014 the trend everyone agrees on."
    },
    {
      "label": "Robotics & AI",
      "etf": "BOTZ",
      "trend": "sideways",
      "ret3mo": 0.0524,
      "vs_spy": -0.0476,
      "buzz": 37,
      "crowd": "loud",
      "state": "neutral_loud",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways, but getting noisy \u2014 one to watch."
    },
    {
      "label": "Banks",
      "etf": "XLF",
      "trend": "sideways",
      "ret3mo": 0.0395,
      "vs_spy": -0.0604,
      "buzz": 79,
      "crowd": "loud",
      "state": "neutral_loud",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways, but getting noisy \u2014 one to watch."
    },
    {
      "label": "Biotech",
      "etf": "XBI",
      "trend": "sideways",
      "ret3mo": 0.0377,
      "vs_spy": -0.0623,
      "buzz": 27,
      "crowd": "quiet",
      "state": "neutral_quiet",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways \u2014 no clear trend yet."
    },
    {
      "label": "Oil & Gas",
      "etf": "XLE",
      "trend": "sideways",
      "ret3mo": 0.0261,
      "vs_spy": -0.0738,
      "buzz": 36,
      "crowd": "quiet",
      "state": "neutral_quiet",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways \u2014 no clear trend yet."
    },
    {
      "label": "Copper",
      "etf": "COPX",
      "trend": "sideways",
      "ret3mo": 0.0086,
      "vs_spy": -0.0913,
      "buzz": 35,
      "crowd": "quiet",
      "state": "neutral_quiet",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways \u2014 no clear trend yet."
    },
    {
      "label": "Utilities & Power",
      "etf": "XLU",
      "trend": "sideways",
      "ret3mo": -0.0445,
      "vs_spy": -0.1444,
      "buzz": 15,
      "crowd": "quiet",
      "state": "neutral_quiet",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways \u2014 no clear trend yet."
    },
    {
      "label": "Defense",
      "etf": "ITA",
      "trend": "sideways",
      "ret3mo": -0.052,
      "vs_spy": -0.1519,
      "buzz": 19,
      "crowd": "quiet",
      "state": "neutral_quiet",
      "light": "grey",
      "emoji": "\u26aa",
      "verdict": "Going sideways \u2014 no clear trend yet."
    },
    {
      "label": "AI Software",
      "etf": "IGV",
      "trend": "down",
      "ret3mo": 0.0896,
      "vs_spy": -0.0103,
      "buzz": 50,
      "crowd": "loud",
      "state": "hype",
      "light": "amber",
      "emoji": "\ud83d\udfe1",
      "verdict": "Lots of buzz but the price is falling \u2014 careful, this is a hype trap."
    },
    {
      "label": "Homebuilders",
      "etf": "XHB",
      "trend": "down",
      "ret3mo": -0.0164,
      "vs_spy": -0.1163,
      "buzz": 11,
      "crowd": "quiet",
      "state": "dead",
      "light": "red",
      "emoji": "\ud83d\udd34",
      "verdict": "Falling and forgotten \u2014 nothing happening here."
    },
    {
      "label": "Nuclear & Uranium",
      "etf": "URA",
      "trend": "down",
      "ret3mo": -0.0711,
      "vs_spy": -0.1711,
      "buzz": 21,
      "crowd": "quiet",
      "state": "dead",
      "light": "red",
      "emoji": "\ud83d\udd34",
      "verdict": "Falling and forgotten \u2014 nothing happening here."
    },
    {
      "label": "Bitcoin",
      "etf": "IBIT",
      "trend": "down",
      "ret3mo": -0.1155,
      "vs_spy": -0.2155,
      "buzz": 88,
      "crowd": "loud",
      "state": "hype",
      "light": "amber",
      "emoji": "\ud83d\udfe1",
      "verdict": "Lots of buzz but the price is falling \u2014 careful, this is a hype trap."
    },
    {
      "label": "Silver",
      "etf": "SIL",
      "trend": "down",
      "ret3mo": -0.2168,
      "vs_spy": -0.3168,
      "buzz": 70,
      "crowd": "loud",
      "state": "hype",
      "light": "amber",
      "emoji": "\ud83d\udfe1",
      "verdict": "Lots of buzz but the price is falling \u2014 careful, this is a hype trap."
    },
    {
      "label": "Gold Miners",
      "etf": "GDX",
      "trend": "down",
      "ret3mo": -0.2223,
      "vs_spy": -0.3223,
      "buzz": 89,
      "crowd": "loud",
      "state": "hype",
      "light": "amber",
      "emoji": "\ud83d\udfe1",
      "verdict": "Lots of buzz but the price is falling \u2014 careful, this is a hype trap."
    }
  ]
};
